language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: aasorg/hacks-collector
        branch: master

env:
    global:
        - secure: "qBl+y/9H9OgMXoEnUP5tpy85hBCUlMftNy3HEBxhcFO4Ya1zmEJniA4pKieLoCg2lqp1JbSmspkl8SQIncIq47+E0RCtR9w18PTpkzbJAUA+AzlEqMtN/oE/UPvBjOc5xxhAZQJ8YaBhQYuLt4bO8nGW9oPObxV9aT96ah+fqLtMTonbbVn0IJa5kPf5mPiGjf3Jm2lPnJpIJW9xubThiYOO9ixFe0+YmwfdYlFhq3WEn05aZerIRpowkGQlwRpzmmq9o3pzkDBdxSkfGMqEwAmbkwzAYkgx7bqa0zCaZJAAjYINZHfmaU/HOHM/nJqczKkCm/s7geJL7rAUy+FsjR4MPM3QfcqIBUPmIRGoQJWPVneAuH4tf6kR9i/mmQZSltdcJ5XO5zRyPuQQvb7ZttZs2+EAE00zKLV5zvxmq6ECNMrnCl8Vm3h4aJ2Ovq80oR6zp12ocWIJAYUGztF3Gpvk/nvWI/Lil0W/nPgIGcMZqN4Ga0+nOPbCNrjtwqCKvevU/5gBx6R2wgyNoOOV/QCUMwyfszHaITWbIHvn2855IB22ue04sAEMaH4EaHh0EmPRtULa3j9QDpVP+YwFfOoOp7BEXsI1v/VSzghvRGin2zM6GhvcuDqxbnOkvV+LDgfMeYE3EPBuAxc5M4YqnLg37qDs7txaiekcpK1+yOA="
