language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: dotastro/hack-list
        branch: master

env:
    global:
        - secure="bocUIf281s5HfRFaWLdQzkfgcRQnIHpA49PFuWlGiHnrlaYVkAtRoHiuwP7b4oqMON5sm/wLzZAf/hDD2gcosI21srHDRUD4HYwisNTj16uecGvB8K+GfQi3U/R1vuAVYQDY4pwEzBNgCKfwMsQavsRtJtlcAbNduN52HVvfURjCN7wc7PEPRJvpAVejB2P2AYXtys/pXXj9MAgHFeIPaDjWR/kEqAKC0xjVHsaawFzwG6a0RTSENob/ovMZSr1NbSdSA+z/yGJEl40CwXhoXs/tF7KE4CYw0ZGyXXJduFGEOiqu2+V1r+kjr3tJU0KWYe0BlPBtiaeao5N5zPfAmqLfX++D5XDOPJcywqT2tIRH95zq3ry2NwbQ2dmQ05+6d+ez1bc5dhHKJTERrrhazzM5vRU0Yn76pnNEDETO9x5tmEyWUwd72b5McDj4RS0C2Ht4cghP+Wn20flDaaKp7eoKP7FtWA0TfC4KQoZCEQU5chsKeowtrSg4Gj/31D7kgCtxR0WcOUG+c4GTJkJG6c2HqZi/w+plsmrNOBgfCSMzJVYWpYUFdH9eUskvVxtY0WobyLMqs1m3QbYTHuCS0kQzzzLHlhAc0qbvoZHG7q8bb9cm4ZZNZRFSMz0XBs08SHfuOWIM3pesp4qEBjYb9kCz6QHSEooMiPkYIe0s39A="
        - GH_REF=github.com/dotastro/hack-list.git
