language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2 pyyaml

script:
  - python validate_entries.py

deploy:
    provider: script
    script: ./travis_deploy
    on:
        repo: dotastro/hack-list
branch: master
