language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: dotastro/hacks-collector
        branch: master

env:
    global:
        - secure: "RW9NcqEgKHM4FDWhCWj45aDJlPPPZVDHoyKfT/P89GbMiz6xZKO1ldTAEW2yHQywo8n7KpTjff8NPGIjMYti7OLB4gIRX6o3WSfODJTBGjVQb8bC6M0QOwkko3q1KefK+cvmMC4PdlIk9asFBJ3M1uub2J3JrVkmJItaKxUNSC4S8vjAWj9Or++m8H8ZQabZUH9WHL9M5S+KT6WuLyCWpI/v+SOJrvPvHaLpaZ0THPXIg0+rQDprktaGquB3FHT5RFF11FiUSUQNJy52Lytqdymz1SAKwrlNNzTS13KbH7KnfOTjKGR7jOG8m8y0+/Bpxjozpv+vhlG7ALnmanUM2BAN15CBryu4aZPj2Xsm+wl+l29SzfQXTfQKRYfNr87wfvtdWyob9WKEv4D+mDfrEWplwlrUkXDWqoDyAitNRHeQ7JXjGKVKkmIKGkln7x/fcDcvhqA9/wY692tbwPd8KzGC1noAQ39rX3dkcG+Qt/kc7CIDztHuXm+5rS4FdfLyNuUcFXjz0Q2hwjFSJUx5EzrLzfa4pOazse5d9Nq3Uli4QuG1gqwfBJ2xzTtsqBxNUzAnSjXo9RvcEI7SfvBKYokg1wLx+oV7xqbgHaHdcXBC31wQGyxc4bd4+ntKRw3HY1a/8VkhYN4dzaE6Gx6USLkcEdys8ySDom8k35/zkLk="
        - GH_REF=github.com/dotastro/hacks-collector.git
