language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: aasorg/hacks-collector
        branch: master

env:
    global:
        - secure: ""
