language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: ./travis_deploy
    on:
        repo: dotastro/hack-list
        branch: master

env:
  global:
    secure: CvKgC+HWMHERWh+QxFC+vj5MaFJgWqEqRPTzzfV6M4YRoG0rWWu1Y6MNjNcox3tLFGWpUe/F31d0WAhsr5lO+enMWllt2u0WnD8UKUxFRmhbJSu14Daz3qWBmUPFt3RLO0jK8HJJ+hlX+RghHe5H7GbVb9bZA7QA/IlzvXrFWB19Zfhsx4C+t7R4/1quxjQfxk8Q3oET+oebv0zmhb/JCnrZty23cZFOl9uPUikRZsGhkOxcAG0cCNGms5Zo2AJJXSL9hJyYg/LnYmmW2XcGSkFfKE2PpL715bW6rets2zd4vH3DCjEwAi4ZbA3nti139Aucaf/S69s5GzZRCAOx98vUxWYmqQxsZ28VipCB5+zz1NusAe25DzZJwMB3pJT4ovuFbysjFJAObM+oaX2bENRmY5xEWdnVDcmcwyAzq7DfgQsUKJm9S0lrH3lMNH/q7wOqXergCVFtDehgMdFkI+EjvxfPpbwI0p9sFVm13obSlT4FSGkQL6ClxeX/kzCqph/I6AmCXfIQR+knrSwMfCn+RrssKkMg2FDidpnYAkqP+Qj4q7bFXfnsnWg55CE7qu3RU3WT4O7zMa2mSKuPsCEydnaIyChGqHsPlpDkOSrIC559Z4NHCuuvoQXF4nWdlhj0YB3sVzvlLYjGla32mCHqmi7pG3RFiY1yljWVHHk=
    GH_REF: github.com/dotastro/hack-list.git
