language: python

python:
  - 3.5

install:
  - pip install six pyyaml requests markdown2 jinja2

script:
  - python validate_entries.py

deploy:
    provider: script
    script: site_generator/travis_deploy
    on:
        repo: dotastro/hack-list
        branch: master

env:
    global:
        - secure: "LLzjJEo0Vm/q706uhfFhjyqRdrvwttRET1bc1E5kS/we159nN2o1sOqIxlmlcMwGLy1HF4T9jijgEba6BIr6KnVXqg38trIR4FOHasfMOrv8o2bYijoFpD22Exwp1zbCbw2TM5HCBxDkPSFHoVx/AIQRm/0un+GEG1BEnkefDpD6dZbqk/Um7DZdW/xIjtMy6iemDmQ+irlBzbsYwAQ0tc25BwJ6Zzp95YoHX5wI40xOTtUrClwz9D7yiusMZmcIDL1i6gDrpkaGLGaancI3fN35CGsvTMwP68HA/c0aGiSDtakrxDlW5kFdATG+jh/HZ5nmy602crNXIOxIDZQIgYhwneC/UFluQWEyii9MIDmIynVONZFotewXSE/ZJ30hHkOviL3/cqtIjp+e6IiPLMQ36ZbyfWNyVHOjHJjVdBQ8LQMq2bzjvPij4GQjfl6mW/FZ/XFGETSsOmPenDMy+ybUaxM3s4lEnU8F0YPDZ1DkUjOZ9q4VBw6zcc4qigksgHgwpt91ibLU14+P3q4hsVsok5UtHHs4hJUHnbw8oB8QamfbtK8k/tT3beItAeLnlYAWdPJIVBnl8rVGW97/fcGKFhAJZ5oG1mNclmr4mRZG1mPx3+KIj0/lvcrPd4kmjNJz1AZb9pnMxVmHK73BavGlyBdLjcfeKU+XM3Aa2Ko="
        - GH_REF=github.com/dotastro/hack-list.git
